// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Barra lateral generada automáticamente desde la estructura de archivos
  docs: [{type: 'autogenerated', dirName: '.'}],

  // También puedes mantener la generación automática si prefieres
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Ejemplo de barra lateral manual comentada
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
